const TRIP_START = new Date('2026-10-07T00:00:00');
const defaultTasks = [
 {id:'disney',title:'Book Tokyo Disneyland tickets',note:'Ticket window and availability should be checked.',category:'Bookings',due:'2026-08-07',done:false,link:'https://www.tokyodisneyresort.jp/en/ticket/index.html'},
 {id:'aoniyoshi',title:'Reserve Aoniyoshi train',note:'Reserve when the booking window opens.',category:'Transport',due:'2026-09-06',done:false,link:'https://www.kintetsu.co.jp/foreign/english/aoniyoshi/'},
 {id:'glanta',title:'Book Glänta ring workshop',note:'Confirm the Tokyo workshop and preferred date.',category:'Bookings',due:'2026-08-15',done:false,link:''},
 {id:'esim',title:'Buy eSIM',note:'Choose Japan + Korea coverage or separate plans.',category:'Digital',due:'2026-09-20',done:false,link:''},
 {id:'ryokan-food',title:'Confirm vegetarian ryokan meals',note:'Send dietary requirements before arrival.',category:'Bookings',due:'2026-08-31',done:false,link:''},
 {id:'passport',title:'Save passport copies offline',note:'Store secure copies in Travel Wallet.',category:'Documents',due:'2026-09-15',done:false,link:''},
 {id:'insurance',title:'Add travel insurance',note:'Policy and emergency contact details.',category:'Documents',due:'2026-09-10',done:false,link:''},
 {id:'cash',title:'Plan JPY and KRW cash',note:'Keep some cash for temples and smaller shops.',category:'Money',due:'2026-09-25',done:false,link:''},
 {id:'adapter',title:'Pack travel adapter',note:'Japan uses Type A; Korea commonly uses Type C/F.',category:'Packing',due:'2026-10-01',done:false,link:''},
 {id:'maps',title:'Download offline maps',note:'Osaka, Kyoto, Fuji, Tokyo and Seoul.',category:'Digital',due:'2026-10-02',done:false,link:''},
 {id:'flight-seoul',title:'Confirm Tokyo → Seoul flight',note:'Check baggage allowances for all bags.',category:'Transport',due:'2026-08-01',done:true,link:''},
 {id:'visa',title:'Japan visa schedule prepared',note:'Schedule of stay completed.',category:'Documents',due:'2026-07-10',done:true,link:''}
];
const cats=['Bookings','Documents','Packing','Money','Digital','Transport'];
let state={view:'home',tasks:JSON.parse(localStorage.getItem('pc_tasks')||'null')||defaultTasks};
const app=document.getElementById('app');
function save(){localStorage.setItem('pc_tasks',JSON.stringify(state.tasks))}
function daysUntil(){return Math.max(0,Math.ceil((TRIP_START-new Date())/86400000))}
function pct(){return Math.round(state.tasks.filter(t=>t.done).length/state.tasks.length*100)}
function nextTask(){return state.tasks.filter(t=>!t.done).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'))[0]}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function go(v){state.view=v;render();scrollTo({top:0,behavior:'smooth'})}
function nav(){return `<nav class="bottom-nav" aria-label="Main navigation">
<button class="${state.view==='home'?'active':''}" onclick="go('home')"><span>⌂</span><small>Home</small></button>
<button class="${state.view==='journey'?'active':''}" onclick="go('journey')"><span>🚆</span><small>Journey</small></button>
<button class="${state.view==='chapter'?'active':''}" onclick="go('chapter')"><span>▣</span><small>Chapter</small></button></nav>`}
function topbar(){return `<header class="topbar"><div class="brand">Sakura 🌸<small>Our Honeymoon Journal</small></div><div class="top-actions"><button class="icon-btn" onclick="go('readiness')" aria-label="Trip readiness">✓</button><button class="icon-btn" onclick="go('wallet')" aria-label="Travel Wallet">▣</button></div></header>`}
function home(){const n=nextTask();app.innerHTML=`<main class="app">${topbar()}
<section class="hero"><img src="assets/kamakura-hero.jpg" alt="Kamakura train"><div class="hero-weather"><strong>22°</strong><span>Osaka preview · Sunny</span></div><div class="hero-copy"><h1>${daysUntil()} days until our adventure</h1><p>Kamakura train · the beginning of our story</p></div></section>
<section class="card"><div class="section-head"><h2>Trip Readiness</h2><button class="text-btn" onclick="go('readiness')">Open →</button></div><div class="readiness-summary"><div class="ring" style="--pct:${pct()}"><strong>${pct()}%</strong></div><div><strong>${pct()}% Ready to Go</strong><div class="muted" style="font-size:12px;margin-top:4px">${state.tasks.filter(t=>t.done).length} of ${state.tasks.length} complete</div></div></div><div class="priority"><div class="priority-label">Today's Priority</div><h3>${n?.title||'Ready to go'}</h3><p>${n?.note||'All preparation tasks are complete.'}</p>${n?`<div class="button-row">${n.link?`<button class="primary" onclick="window.open('${n.link}','_blank')">Open</button>`:''}<button class="secondary" onclick="toggleTask('${n.id}')">Mark complete</button></div>`:''}</div></section>
<section class="card"><div class="section-head"><h2>Journey Progress</h2><button class="text-btn" onclick="go('journey')">View →</button></div><div class="journey-scroll"><div class="track"></div><div class="stops">${[['✈️','Toronto'],['🐙','Osaka'],['⛩','Kyoto'],['🗻','Fuji'],['🗼','Tokyo'],['🏙','Seoul']].map((s,i)=>`<div class="stop ${i===1?'current':''}"><div class="dot">${s[0]}</div>${s[1]}</div>`).join('')}</div></div></section>
<section class="tile-grid"><button class="tile" onclick="toast('Stay screen is part of Sprint 2')"><img src="assets/hotel.jpg" alt="Hotel room"><div class="tile-copy"><strong>Stay</strong><small>Basecamp and check-in</small></div></button><button class="tile" onclick="toast('Taste & Moments is part of Sprint 5')"><img src="assets/ramen.jpg" alt="Ramen"><div class="tile-copy"><strong>Taste</strong><small>Vegetarian food nearby</small></div></button><button class="tile" onclick="toast('Explore is part of Sprint 5')"><img src="assets/osaka.jpg" alt="Osaka Castle"><div class="tile-copy"><strong>Explore</strong><small>Places and essentials</small></div></button><button class="tile" onclick="go('wallet')"><img src="assets/concierge.jpg" alt="Travel documents"><div class="tile-copy"><strong>Travel Wallet</strong><small>Tickets and documents</small></div></button></section>
<section class="card"><div class="section-head"><h2>Budget Train</h2><span class="muted">58% used</span></div><div class="budget-track"><span class="budget-train">🚃</span></div><div class="budget-meta"><span>Flights</span><span>Stay</span><span>Food</span><span>Shopping</span></div></section>${nav()}</main>`}
function readiness(){const n=nextTask();app.innerHTML=`<main class="app"><div class="page-title"><button class="back" onclick="go('home')">←</button><h1>Trip Readiness</h1></div><section class="card"><div class="readiness-summary"><div class="ring" style="--pct:${pct()}"><strong>${pct()}%</strong></div><div><strong>${daysUntil()} days remaining</strong><div class="muted" style="font-size:12px;margin-top:4px">${pct()}% Ready to Go</div></div></div></section><section class="card"><div class="section-head"><h2>Today's Priority</h2></div>${n?`<div class="priority" style="margin-top:0"><div class="priority-label">Due ${formatDate(n.due)}</div><h3>${n.title}</h3><p>${n.note}</p><div class="button-row">${n.link?`<button class="primary" onclick="window.open('${n.link}','_blank')">Open booking</button>`:''}<button class="secondary" onclick="toggleTask('${n.id}')">Mark ✓</button></div></div>`:'<p>Everything is complete.</p>'}</section><section class="card"><div class="section-head"><h2>Due Soon</h2><button class="text-btn" onclick="go('due')">View all →</button></div></section><section><div class="section-head" style="padding:0 3px"><h2>Getting Ready</h2></div><div class="category-grid">${cats.map(c=>{const ts=state.tasks.filter(t=>t.category===c),d=ts.filter(t=>t.done).length;return `<button class="category" onclick="openCategory('${c}')"><div class="emoji">${icon(c)}</div><strong>${c}</strong><small>${d} of ${ts.length} complete</small><div class="progress"><i style="--p:${ts.length?d/ts.length*100:0}%"></i></div></button>`}).join('')}</div></section>${nav()}</main>`}
function due(){const list=state.tasks.filter(t=>!t.done).sort((a,b)=>a.due.localeCompare(b.due));app.innerHTML=`<main class="app"><div class="page-title"><button class="back" onclick="go('readiness')">←</button><h1>Due Soon</h1></div><section class="card">${list.map(taskRow).join('')}</section>${nav()}</main>`}
function openCategory(c){state.category=c;state.view='category';render();scrollTo(0,0)}
function category(){const list=state.tasks.filter(t=>t.category===state.category);app.innerHTML=`<main class="app"><div class="page-title"><button class="back" onclick="go('readiness')">←</button><h1>${state.category}</h1></div><section class="card">${list.map(taskRow).join('')}</section>${nav()}</main>`}
function taskRow(t){return `<div class="task"><button class="check ${t.done?'done':''}" onclick="toggleTask('${t.id}')">${t.done?'✓':''}</button><div class="task-body"><strong>${t.title}</strong><small>${t.note}</small><span class="badge">${formatDate(t.due)}</span></div>${t.link&&!t.done?`<button class="text-btn" onclick="window.open('${t.link}','_blank')">Open</button>`:''}</div>`}
function journey(){const cities=[['🐙','Osaka','Oct 7–10','3 nights','assets/osaka.jpg','Next Chapter'],['⛩','Kyoto','Oct 10–12','2 nights','assets/concierge.jpg',''],['🗻','Fuji / Hakone','Oct 12–16','4 nights','assets/kamakura-hero.jpg',''],['🗼','Tokyo','Oct 16–21','5 nights','assets/hotel.jpg',''],['🏙','Seoul','Oct 21–25','4 nights','assets/ramen.jpg','']];app.innerHTML=`<main class="app"><div class="page-title"><button class="back" onclick="go('home')">←</button><h1>Our Journey</h1></div><p class="muted" style="margin:-5px 3px 15px">Choose a chapter</p>${cities.map(c=>`<button class="tile" style="display:block;width:100%;height:190px;margin-bottom:12px" onclick="toast('${c[1]} chapter opens in Sprint 2')"><img src="${c[4]}" alt="${c[1]}"><div class="tile-copy"><strong>${c[0]} ${c[1]}</strong><small>${c[2]} · ${c[3]}${c[5]?' · '+c[5]:''}</small></div></button>`).join('')}${nav()}</main>`}
function chapter(){app.innerHTML=`<main class="app"><div class="page-title"><button class="back" onclick="go('home')">←</button><h1>Today's Chapter</h1></div><section class="card"><div class="section-head"><h2>Today's Essentials</h2></div><p>☀️ 22° · Weather details closer to the trip</p><p>🎫 No JR Pass needed today</p><p>💴 Carry some cash</p></section>${[['🌅 Morning',[['Coffee first','assets/ramen.jpg'],['Osaka Castle','assets/osaka.jpg']]],['☀️ Afternoon',[['Namba & Shinsaibashi','assets/concierge.jpg'],['Vegetarian lunch','assets/ramen.jpg']]],['🌇 Evening',[['Dotonbori walk','assets/concierge.jpg'],['Return to basecamp','assets/hotel.jpg']]]].map(g=>`<section class="chapter-group"><h2>${g[0]}</h2>${g[1].map(x=>`<div class="experience"><img src="${x[1]}" alt=""><div><strong>${x[0]}</strong><small>Tap for details when city modules are connected.</small></div></div>`).join('')}</section>`).join('')}${nav()}</main>`}
function wallet(){const comps=[['🛂','Documents','Passport, visa, insurance'],['🎫','Tickets & Passes','Flights, trains and activities'],['🏨','Reservations','Hotels, dining and experiences'],['💳','Payments','Cash, cards and tax-free'],['🚨','Emergency','Contacts and translation cards'],['↓','Downloads','Offline maps and PDFs']];app.innerHTML=`<main class="app"><div class="page-title"><button class="back" onclick="go('home')">←</button><h1>Travel Wallet</h1></div><section class="card"><div class="section-head"><h2>Ready Now</h2><button class="text-btn" onclick="toast('Upload flow will be enabled in Wallet sprint')">+ Add</button></div><div class="ready-strip"><div class="ready-item"><strong>🛂 Passport</strong><small>Document shortcut</small></div><div class="ready-item"><strong>🏨 Osaka Hotel</strong><small>Oct 7 check-in</small></div><div class="ready-item"><strong>✈️ Flight</strong><small>Toronto → Osaka</small></div></div></section><div class="wallet-grid">${comps.map(c=>`<button class="wallet-card" onclick="toast('${c[1]} opens in Wallet sprint')"><div class="emoji">${c[0]}</div><strong>${c[1]}</strong><small>${c[2]}</small></button>`).join('')}</div>${nav()}</main>`}
function toggleTask(id){const t=state.tasks.find(t=>t.id===id);if(t){t.done=!t.done;save();toast(t.done?'Marked complete':'Marked incomplete');render()}}
function icon(c){return {Bookings:'🎟',Documents:'📄',Packing:'🧳',Money:'💳',Digital:'📱',Transport:'🚆'}[c]||'•'}
function formatDate(d){return new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}
function render(){({home,readiness,due,category,journey,chapter,wallet}[state.view]||home)()}
window.go=go;window.toggleTask=toggleTask;window.openCategory=openCategory;render();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
